<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Dish>
 */
class DishFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => $this->faker->randomElement([
                'Frango com Batata Doce',
                'Omelete de Claras',
                'Peito de Frango Grelhado',
                'Salmão com Legumes',
                'Quinoa com Vegetais',
                'Frango Assado com Legumes',
                'Arroz Integral com Peito de Frango',
                'Salmão Grelhado com Aspargos',
                'Peito de Peru com Brócolis',
                'Carne Moída com Batata Doce',
                'Espaguete de Abobrinha com Molho de Tomate',
                'Frango ao Curry com Arroz Integral',
                'Taco de Alface com Carne Moída',
                'Sopa de Abóbora com Gengibre',
                'Salada de Atum com Folhas Verdes',
                'Sanduíche de Peito de Peru e Abacate',
                'Ceviche de Salmão',
                'Frango Grelhado com Quinoa',
                'Sopa de Frango com Legumes',
                'Bowl de Açaí com Granola e Frutas',
                'Espetinho de Frango com Legumes',
                'Salada de Quinoa com Tomate e Pepino',
                'Peixe Assado com Arroz de Couve-flor',
                'Batata Doce Recheada com Carne Moída',
                'Tigela de Buddha com Grão de Bico',
                'Frango ao Limão com Aspargos',
                'Salmão ao Forno com Abobrinha',
                'Almôndega de Frango com Molho de Tomate',
                'Sopa de Lentilha com Espinafre',
                'Pasta de Abacate com Salmão Defumado',
                'Frango Xadrez com Arroz Integral',
                'Feijão Tropeiro com Couve',
                'Frango à Parmegiana Light',
                'Salada de Frango com Abacate',
                'Peito de Frango com Arroz de Amêndoas',
                'Wrap de Alface com Peito de Peru',
                'Carne de Panela com Batata Doce',
                'Quinoa com Frango e Espinafre',
                'Tortilha de Milho com Carne e Legumes',
                'Salmão com Purê de Abóbora',
                'Tartar de Atum com Abacate',
                'Strogonoff de Frango Light',
                'Filé Mignon Grelhado com Brócolis',
                'Panqueca de Aveia com Banana',
                'Arroz de Couve-flor com Frango',
                'Salada de Grão de Bico com Tomate',
                'Bife de Peito de Frango com Abóbora',
                'Risoto de Quinoa com Cogumelos',
                'Bowl de Açaí com Banana e Mel',
                'Pizza de Abobrinha com Molho de Tomate',
                'Sopa de Abóbora com Queijo Cottage',
                'Panqueca Proteica de Frango',
                'Salada de Grão de Bico com Peixe',
                'Salmão ao Molho de Alho e Limão',
                'Feijão Preto com Arroz Integral',
                'Wrap de Frango com Abacate',
                'Frango Grelhado com Batata Doce e Aspargos',
                'Salmão Defumado com Cream Cheese',
                'Abobrinha Recheada com Carne Moída',
                'Sopa de Tomate com Manjericão',
                'Filé de Peixe com Purê de Abóbora',
                'Lasanha de Abobrinha com Carne Moída',
                'Bowl de Frango com Quinoa e Vegetais',
                'Arroz Integral com Feijão e Abóbora',
                'Frango Empanado com Farinha de Amêndoas',
                'Bife de Frango com Abobrinha',
                'Batata Doce Assada com Frango',
                'Filé de Peixe com Espinafre',
                'Pasta de Abóbora com Carne Moída',
                'Salada de Atum com Grão de Bico',
                'Omelete de Espinafre e Cogumelos',
                'Frango com Molho de Mostarda e Mel',
                'Sopa de Abóbora com Frango',
                'Carne Assada com Purê de Batata Doce',
                'Salmão Grelhado com Couscous',
                'Salada de Frango com Quinoa',
                'Arroz Integral com Salmão Defumado',
                'Grão de Bico com Tomate e Coentro',
                'Peito de Frango com Salsinha e Limão',
                'Sopa de Ervilha com Bacon',
                'Carne de Panela com Purê de Batata Doce',
                'Frango com Legumes ao Forno',
                'Sopa de Abóbora com Queijo Parmesão',
                'Frango Assado com Batata Doce e Alho',
                'Salada de Alface com Peito de Peru',
                'Risoto de Arroz Integral com Cogumelos',
                'Lasanha de Berinjela com Carne Moída',
                'Peito de Frango com Molho de Iogurte',
                'Arroz de Couve-flor com Carne Moída',
                'Salmão ao Vapor com Abacate',
                'Salada de Frango com Abóbora',
                'Quinoa com Legumes e Tofu',
                'Tigela de Frango com Espinafre e Quinoa',
                'Frango com Abacate e Alface',
                'Sopa de Lentilha com Frango',
                'Bowl de Açaí com Frutas Vermelhas',
                'Taco de Frango com Alface e Tomate',
                'Salmão Defumado com Cebola Roxa',
                'Frango com Molho de Mostarda',
                'Carne Moída com Abóbora',
                'Pão de Queijo Low Carb',
                'Peito de Frango Grelhado com Espinafre',
                'Salada de Peixe com Limão e Azeite',
                'Strogonoff de Carne com Creme de Leite Light'
            ]),
            'description' => $this->faker->sentence(),
            'preparation_method' => $this->faker->paragraph(),
            'created_by' => 1,
        ];
        
    }
}
